// Code generated by mockery v2.28.2. DO NOT EDIT.

package mocks

import (
	models "api.quota-quick/api/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ContSaver is an autogenerated mock type for the ContSaver type
type ContSaver struct {
	mock.Mock
}

// SaveContainer provides a mock function with given fields: cntr
func (_m *ContSaver) SaveContainer(cntr models.Container) error {
	ret := _m.Called(cntr)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Container) error); ok {
		r0 = rf(cntr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewContSaver interface {
	mock.TestingT
	Cleanup(func())
}

// NewContSaver creates a new instance of ContSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewContSaver(t mockConstructorTestingTNewContSaver) *ContSaver {
	mock := &ContSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
